### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by diwu86** [Sage/carbon-factory#108]
Hi when I run " npm install sage/carbon-factory -g" on a windows machine, I got error:
`npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  sage/carbon-factory resetting remote C:\Users\di\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sage-carbon-factory-git-fb06ad51 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
`
Because I cannot get carbon installed, I get error `Error: Cannot find module 'C:\Users\di\AppData\Roaming\npm\node_modules\carbon-factory\src\cli-app'` when I do `carbon app myapp`. Does anyone know how to fix this? Thanks

**Comment by FredericHertz** [comment]
Hi, I had the same issue. I just copy 'C:\Users\di\AppData\Roaming\npm\node_modules\carbon-factory\src\carbon-app.js' to cli-app.js.

**Comment by ianoxley** [comment]
Since this issue was created the installation command has changed to:

``` bash
npm install -g carbon-factory
```

Installation on Windows should succeed without error.

The second issue i.e. `Error: Cannot find module 'C:\Users\di\AppData\Roaming\npm\node_modules\carbon-factory\src\cli-app`, still persists though

**Comment by andrewjtait** [comment]
Fixed with https://github.com/Sage/create-carbon-app
