### ISSUE TITLE
Improve test output

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon-factory#80]
we should:
- reduce the React stack traces and remove browserify cache output, focusing just on the line-numbers and actual error in the code as this is the stuff we need to see
- improve colourification
- better test fail summary
- better console log output, incorporating `toJS()` calls and recursive depth into objects to minimise `-b chrome` type debugging

Something like this, or similar, could be useful: https://www.npmjs.com/package/jasmine-console-reporter

**Comment by andrewjtait** [comment]
Hopefully this has improved with the introduction of Jest and can be closed?

**Comment by toni-leigh** [comment]
Yes I think so, `console.log` is still a bit derp, as the following shows:

```
      { '1':
         { contactPaymentsPostIsOpen: true,
           displayed_as: 'Test Invoice',
           outstanding_amount: '691.00',
           payment_type: 'receipt',
           write: { '2': [Object] } }, <<<<<< because I don't want to look at that of course!
        association_id: '2' }
```

But apart from that it seems fine
